### ISSUE TITLE
Expected release date?

### ISSUE THREAD

**Issue by Bluscream** [rhysperry111/spicetify-gui#1]
I really want this to be a thing!

**Comment by rhysperry111** [comment]
I could have it working by the end of the week (but it wouldn't be pretty). Sorry for taking so long, I have been tied up because I am focusing on school (GCSE exams this year). I'll be honest, I totally forgot about this projects but because there seems to be some demand for this I will try and spend as much time as fit in.

**Comment by rhysperry111** [comment]
Plan is (allow a week or two deviation):
- Get Alpha 2 out by the end of the week (will be usable but NOT pretty)
- Get Alpha 3 out in a month or so (will be usable and sort of pretty)
- Move onto Betas for bug testing (no guaranteed time)
- Release V1.0.0 and pray that no bugs exist (only if I still have some sanity left that far into the future)

**Comment by Bluscream** [comment]
:+1:

_Sent from my TAB 2 A10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rhysperry111** [comment]
Just asking, what OS do you use (I am primarily targeting Linux)
